// Tileset pals generated by mkts [nes mode]
// Copyleft 2015 The Mojon Twins
 
const unsigned char ts_pals [] = {
	 0
,  0
,  0
,  0
,  0
,  0
,  1
,  1
,  0
,  0
,  0
,  0
,  0
,  1
,  0
,  3
, 
	 3
,  2
,  2
,  2
,  2
,  3
,  3
,  3
,  3
,  0
,  3
,  0
,  3
,  0
,  0
,  2
, 
	 0
,  0
,  0
,  0
,  0
,  0
,  0
,  0
,  0
,  0
,  1
,  1
,  3
,  3
,  0
,  0
, 
};
